### ISSUE TITLE
Feature Request: allow `mix chaps.detail` like `mix coveralls.detail`

### ISSUE THREAD

**Issue by bjornrud** [NFIBrokerage/chaps#3]
Hey y'all.  Feel free to bounce this request out of the club, close, or ignore the issue.  

Some places, like codespaces, don't afford the very nice html report. 

If implemented, would expect same behavior with highlighting in terminal like dis.
<img width="665" alt="Screen Shot 2022-03-31 at 11 45 08 AM" src="https://user-images.githubusercontent.com/543421/161107450-1cb5f0d3-3403-43cb-80d1-b6d2d07df874.png">

I respect if targeting yet a different developer environment is beyond scope, and this isn't taken up.

**Comment by the-mikedavis** [comment]
I think chaps should support `chaps.detail` 👍 

I see we still have that mix task module left over from coveralls: https://github.com/NFIBrokerage/chaps/blob/30811414159882d3a1c0254601004c235a8a31ee/lib/mix/tasks.ex#L149-L162

Does `mix chaps.detail` not currently work? It might be a matter of environment, so `MIX_ENV=test mix chaps.detail` might work if `mix chaps.detail` does not. If that works out, we may just need to add a line to the `:preferred_cli_env` `mix.exs` key of apps that use chaps (similar to [here](https://github.com/NFIBrokerage/mint_web_socket/blob/b6eccfc4b3ad1811193feb7434a52ad859bc6ddb/mix.exs#L24))

**Comment by bjornrud** [comment]
chaps.detail did not work yesterday, and we put coveralls in, will see if I can't show a reproduction.

**Comment by bjornrud** [comment]
🤦 Fix was misconfiguration of: 
`test_coverage: [tool: Chaps]`

  ```shell
someone@d4761111196d:/workspaces/thinger# mix chaps.detail
** (Mix) The task "chaps.detail" could not be found
someone@d4761111196d:/workspaces/thinger# mix help | grep chaps
someone@d4761111196d:/workspaces/thinger# mix chaps
** (Chaps.InvalidConfigError) Please specify 'test_coverage: [tool: Chaps]' in the 'project' section of mix.exs
    lib/mix/tasks.ex:32: Mix.Tasks.Chaps.do_run/2
    (mix 1.13.3) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
someone@d4761111196d:/workspaces/thinger# MIX_ENV=test mix chaps.detail
** (Chaps.InvalidConfigError) Please specify 'test_coverage: [tool: Chaps]' in the 'project' section of mix.exs
    lib/mix/tasks.ex:32: Mix.Tasks.Chaps.do_run/2
    (mix 1.13.3) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
someone@d4761111196d:/workspaces/thinger# 
```

The same error persisted even when adding `"chaps.detail": :test,` same with chaps and chaps.html...  Leaving my mistake in public for shame or future help.  Thanks for the care, @the-mikedavis
